apiVersion: apps/v1
kind: Deployment
metadata:
  name: okoca-app-deployment
  labels:
    app: okoca
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: okoca
  template:
    metadata:
      labels:
        app: okoca
    spec:
      containers:
      - name: okoca
        image: wil42/playground:v1
        ports:
        - containerPort: 8888
        # resources:
        #   limits:
        #     cpu: "500m" # 0.5 cpu
        #     memory: "512Mi" # 512 megabytes
        #   requests:
        #     cpu: "100m" # 0.1 cpu
        #     memory: "128Mi" # 128 megabytes
