apiVersion: v1
kind: Service
metadata:
  name: okoca-app-service
  namespace: dev
  labels:
    app: okoca
spec:
  type: LoadBalancer
  selector:
    app: okoca
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
